# Site settings
title: 
header-img: img/home-bg.png
email: 4stacyg@optonline.net
copyright_name: StavroulaTG
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  StavroulaTG
learn_profile: StavroulaTG
email_username: 4stacyg@optonline.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
